//import java.util.InputMismatchException;
//
////package day58_exception2;
////
//public class TryCatchFinally {
////    public static void main (String[] args) {
////        System.out.println("Before try catch");
////        try{
////            System.out.println("Hello From Try block");
////            String str = null;
////            System.out.println(str.length());
////        }catch(Exception e){
////            System.out.println("Exception happened and caught");
////        }
////        System.out.println("After try catch");â€‹
////        try{
////            System.out.println("Hello From Try block");
////            String str = null;
////            assert str != null;
////            System.out.println(str.length());
////        }catch(Exception e){
////            System.out.println("Exception happened and caught");
////        }finally {
////            System.out.println("Finally block. Runs always. Runs if there is Exception or No Exception");
////        }
////    }
//
//    public static void main(String[]args){
//
//        String name = "manuChaeh";
//
//
//    }
////    public static String method1(String nam){
////        String name= "acmAskjca";
////        name=
////    }
//}
//
